apiVersion: batch/v1
kind: Job
metadata:
  name: mcoboarr-${NAME}
spec:
  backoffLimit: 0
  completions: 10
  template:
    metadata:
      labels:
        k8s-app: mcoboarr-${NAME}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mcoboarr-${NAME}
          image: mcoboarr/xgboost:tag84
          command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: AWS_ACCESS_KEY_ID
              value: "..."
            - name: AWS_SECRET_ACCESS_KEY
              value: "..."
          args:
            - >
              python download.py &&
              sleep 1000 &&
              python single_cell.py &&
              python upload.py
          resources:
            limits:
              memory: 400Gi
              cpu: "16"
              nvidia.com/gpu: "1"
            requests:
              memory: 400Gi
              cpu: "16"
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: ephemeral
              mountPath: "/data"
            # SystemV shared memory
            - name: "dshm"
              mountPath: "/dev/shm"
      volumes:
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
      tolerations:
        - key: "nautilus.io/chase-ci"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # Host blacklist
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k8s-chase-ci-04.calit2.optiputer.net
                      - k8s-chase-ci-01.noc.ucsb.edu
                      - k8s-chase-ci-02.calit2.optiputer.net
                      - fiona8-1.calit2.uci.edu
                      - k8s-chase-ci-06.calit2.optiputer.net
